# Generated by Django 5.0.4 on 2024-04-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0004_alter_order_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='products'),
        ),
    ]
